- public/index.html
Minor adjustment to the title.
> chore: remove studio from the title

- src/components/Layout/Layout.jsx
- src/components/Sidebar/Sidebar.jsx
- src/components/SnackbarNotification/SnackbarNotification.jsx
- src/pages/CompareJson/CompareJson.jsx
- src/pages/CompareJson/components/TextInput/TextInput.jsx
- src/pages/CompareJson/components/TextInput/index.jsx
- src/pages/CompareJson/hooks/useCompareJson.js
- src/pages/CompareJson/styles.js
- src/pages/index.js
- src/routes/Routes.jsx
- src/routes/listRoutes.js
[compare-states](https://app.clickup.com/t/23tp41v)
Essa versão inicial da task compara os JSONs inseridos em input pelo usuário. Pro usuário visualizar é necessário visualizar o console do desenvolvedor. No console, vai visualizar os elementos removidos, os elementos adicionados e as propriedades com tipos diferentes.
> Compare states

- src/components/CollapsedTableRow/CollapsedTableRow.jsx
- src/components/Sidebar/Sidebar.jsx
- src/pages/CompareJson/CompareJson.jsx
- src/pages/CompareJson/components/Section/index.jsx
- src/pages/CompareJson/hooks/useCompare.js
- src/services/workflowService.js
Está atualizada com a [PR #5](https://github.com/flow-build/studio/pull/5)
- Sinalizador de Comparação
- O usuário pode visualizar se o comparador está vazio ou não
- Barra de Identificação e Comandos
- O usuário pode pesquisar passando o process id e o stepNumber
- O usuário pode pesquisar passando o process id e o nodeId
> Features compare states

- src/pages/diagram/components/process-state-dialog/index.js
https://app.clickup.com/t/26n65td
> Incluir workflow_name e node_id no modal de estado

- src/pages/dashboard/dashboard.tsx
- src/pages/history/styles.ts
- src/pages/processes/styles.ts
- src/pages/workflows/styles.ts
- src/shared/components/content/content.tsx
- src/shared/components/table/styles.ts
- src/shared/components/table/table.tsx
- Paginação incluída nas tabelas
- A ordenação será realizada em outra task pois será necessário ajuste maior no component da tabela
> Cu 2rhae85 incluir ordenao e paginao nos grids

- src/pages/diagram/hooks/useDiagram.ts
[FBS-17](https://dsd-fdte.atlassian.net/browse/FBS-17?atlOrigin=eyJpIjoiYTM0MzVmMmM2Mzg1NDk3ZDg5ZWYyMjkwMTcyZmFjOWYiLCJwIjoiaiJ9)
> Remover Elementos de Construção quando visualizo Processo

- src/pages/history/history.tsx
- src/pages/history/styles.ts
[FBS-21](https://dsd-fdte.atlassian.net/browse/FBS-21?atlOrigin=eyJpIjoiZjc2YTQ0MmNkNDI5NDY2ZGIyNGMwYTcwZjc1ZGEzYTkiLCJwIjoiaiJ9)
> [FBS-21] - Inclui botão de VOLTAR na tela de histórico

- src/pages/history/hooks/useTable.tsx
- src/store/slices/compare-page.ts
[FBS-18](https://dsd-fdte.atlassian.net/browse/FBS-18?atlOrigin=eyJpIjoiZDZiMjhkODJlYzZjNGQ1OTlhZTlkMWQ5YjA2NWYxY2YiLCJwIjoiaiJ9)
> [FSB-18] Comparar 2 estados do mesmo processo

- src/pages/compare-json/components/Section/index.jsx
- src/pages/compare-json/hooks/useCompare.js
- src/pages/compare-json/index.jsx
[FBS-44] - (https://dsd-fdte.atlassian.net/browse/FBS-44?atlOrigin=eyJpIjoiMDc5Yzc0ZTkxM2VjNDEzNGJiYjZkZDRkZDMwNjc5ZTIiLCJwIjoiaiJ9)
[FBS-44]: https://dsd-fdte.atlassian.net/browse/FBS-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FBS-44] - Preencher o process_id ao navegar entre steps

- src/pages/history/components/collapse-content/collapse-content.tsx
[FBS-48](https://dsd-fdte.atlassian.net/browse/FBS-48?atlOrigin=eyJpIjoiYzI3NTkzYzcxNTVlNDhmMDg4NWVlMDAyYWFjMjk5ZmUiLCJwIjoiaiJ9)
> [FBS-48] - Incluir campo error quando o status é error

- src/pages/workflows/dialogs/start-process/start-process.tsx
[FBS-51] (https://dsd-fdte.atlassian.net/browse/FBS-51?atlOrigin=eyJpIjoiOTU5MjkyMzVjYzEyNDc2ZTg5MzI5NjljMDI0MzQzMmUiLCJwIjoiaiJ9)
[FBS-51]: https://dsd-fdte.atlassian.net/browse/FBS-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FBS-51] - Trocar Labels

- src/pages/processes/hooks/useTable.ts
[FBS-41](https://dsd-fdte.atlassian.net/browse/FBS-41?atlOrigin=eyJpIjoiOGFkODY2ZTUxZDA0NDhjY2JjNWY4MWVlZmY3ZWYxMWEiLCJwIjoiaiJ9)
> [FBS-41] - Trocar Headers do Grid de Processos

- src/pages/diagram/dialogs/properties/properties.tsx
[FBS-67](https://dsd-fdte.atlassian.net/browse/FBS-67?atlOrigin=eyJpIjoiOWU0YjZmNWUwMTgxNGQzZmI4MzI4MDRjNjFhYmIxNGEiLCJwIjoiaiJ9)
> [FBS-67] - Reposicionar Category

- src/pages/compare-json/components/Section/index.jsx
- src/pages/history/history.tsx
- src/store/index.ts
- src/store/slices/process-id.ts
[FBS-68](https://dsd-fdte.atlassian.net/browse/FBS-68?atlOrigin=eyJpIjoiMDdjNTJkZWViMzBiNDMzMGEyYTQ1YzllMzc4OGE1MWEiLCJwIjoiaiJ9)
> [FBS-68] - Input com o campo errado

- src/pages/metabase/metabase.tsx
- src/pages/metabase/styles.ts
[FBS-65](https://dsd-fdte.atlassian.net/browse/FBS-65?atlOrigin=eyJpIjoiMjVjYzcwZjk2OGViNGE0ZDgyYWUzYzBlN2YyYzAzNzIiLCJwIjoiaiJ9)
> [FBS-65]- Aumentar a área do Dashboard

- src/pages/dashboard/components/sidebar/hooks/useSidebar.tsx
- src/pages/diagram/components/header/styles.ts
- src/pages/nodes/components/card/card.tsx
- src/pages/nodes/components/card/index.ts
- src/pages/nodes/components/card/styles.ts
- src/pages/nodes/index.ts
- src/pages/nodes/nodes.tsx
- src/pages/nodes/styles.ts
- src/routes/index.tsx
- src/services/api/index.ts
- src/services/resources/nodes/nodes.ts
[FBS-71](https://dsd-fdte.atlassian.net/browse/FBS-71?atlOrigin=eyJpIjoiY2I5NmQ2OTVkY2FlNGNjZGFmN2U2ZWM5MDE5OTViYmMiLCJwIjoiaiJ9)
> [FBS-71] - Seção Nodes

- src/pages/sign/sign-in/sign-in.tsx
- src/services/resources/diagrams/token/index.ts
- src/services/resources/token/getAnonymous/index.ts
[FBS-88](https://dsd-fdte.atlassian.net/browse/FBS-88?atlOrigin=eyJpIjoiZmI1MDVjMGExM2RhNGViOGJmYjhiN2EwOWE3OTY4NzIiLCJwIjoiaiJ9)
> [FBS-88] - Enviar UUID do actor no Login

- src/pages/settings/settings.tsx
[FBS-76](https://dsd-fdte.atlassian.net/browse/FBS-76?atlOrigin=eyJpIjoiZWY0ZTQxNTNiMjQwNDdjMThhZTg0MDc4ZGI2MTZkNmYiLCJwIjoiaiJ9)
> [FBS-76] - Tornar o servidor do MQTT não obrigatório

- src/pages/diagram/dialogs/save-diagram/save-diagram.tsx
[FBS-85](https://dsd-fdte.atlassian.net/browse/FBS-85?atlOrigin=eyJpIjoiZTNlZGJkNmM0ZWNjNGQ5Mjg0MTdiNDQ4NTZhOTFlZjciLCJwIjoiaiJ9)
> [FBS-85] - Modal não fecha depois de salvar

- src/pages/dashboard/components/header/header.tsx
- src/pages/dashboard/components/header/styles.ts
- src/pages/register/components/sign-in/sign-in.tsx
- src/pages/register/components/sign-in/styles.ts
[FBS-56](https://dsd-fdte.atlassian.net/browse/FBS-56?atlOrigin=eyJpIjoiNTE5ZGNlZDAwOWE4NDAyMWFkZDgxOTdmZDY4ODM2MjQiLCJwIjoiaiJ9)
> [FBS-56] - Integrar Login com AWS Cognito

- src/pages/auth/confirmation-code/confirmation-code.tsx
- src/pages/auth/sign-in/sign-in.tsx
- src/pages/auth/sign-up/sign-up.tsx
[FBS-101](https://dsd-fdte.atlassian.net/browse/FBS-101?atlOrigin=eyJpIjoiMTk2ZTQzNTg0NDI5NGVkNGIyZThmOThmMjkyNjk5MWYiLCJwIjoiaiJ9)
> [FBS-101] - Criar fluxo para usuário não confirmado

- src/pages/settings/settings.tsx
- src/pages/settings/styles.ts
- src/pages/settings/utils/string.ts
[FBS-96](https://dsd-fdte.atlassian.net/browse/FBS-96?atlOrigin=eyJpIjoiZWE4MmIyZmQ5ZmQ5NDc5OTg3OWFjMTZiNTJkZGM0NjYiLCJwIjoiaiJ9)
> [FBS-96] - Loading eterno quando não consegue conectar ao servidor do MQTT

- src/pages/dashboard/components/header/header.tsx
- src/pages/dashboard/components/header/styles.ts
- src/pages/settings/settings.tsx
- src/pages/settings/styles.ts
- src/pages/settings/utils/string.ts
[FBS-104](https://dsd-fdte.atlassian.net/browse/FBS-104?atlOrigin=eyJpIjoiYzM5YjcxZjg3Y2M3NDY3ZjgyZTI4MjcxNTY3YjBiM2QiLCJwIjoiaiJ9)
> [FBS-104] - Click fora da área no botão de logout

- src/pages/auth/sign-in/sign-in.tsx
- src/pages/auth/sign-in/styles.ts
- src/pages/dashboard/components/header/header.tsx
- src/pages/dashboard/components/header/styles.ts
- src/pages/settings/settings.tsx
- src/pages/settings/styles.ts
- src/pages/settings/utils/string.ts
- src/routes/index.tsx
- src/shared/components/button/button.tsx
- src/shared/components/button/styles.ts
[FBS-105](https://dsd-fdte.atlassian.net/browse/FBS-105?atlOrigin=eyJpIjoiOWU2ZGE0NzZmMDFkNDE0NWJiZjc2YmY2MTljNGI1MTciLCJwIjoiaiJ9)
> [FBS-105] - Criar fluxo para click em sign-in enquanto estiver carregando
